### ISSUE TITLE
Handle `EXC_CRASH` exceptions on macOS

### ISSUE THREAD

**Issue by gabrielesvelto** [EmbarkStudios/crash-handling#35]
macOS throws `EXC_CRASH` exceptions in response to other exceptions that hit processes that have already terminated but are still kept alive in the kernel (possibly because there are pending references to them). The macOS kernel sources refer to processes in that state as "corpses" . The original exception is packed into the `EXC_CRASH` extension and delivered to the handler in that form. To support these type of exceptions the following needs to be done:
* The new exception needs to be added to the exception mask
* Issue #31 needs to be fixed first otherwise the subcode will be empty
* [minidump-writer issue #34](https://github.com/rust-minidump/minidump-writer/issues/34) also needs to be fixed so that the minidump writer can properly unpack the original exception

**Comment by Jake-Shadle** [comment]
After a cursory search in the mozilla codebase, there doesn't seem to be any code to actually trigger an `EXC_CRASH`? I added the mask but it would be nice if there is a way I can actually test that the code properly handles it, but seems it might be difficult given your summary of when it would be thrown.

**Comment by gabrielesvelto** [comment]
I couldn't find a way to trigger it but truth be said I didn't try too hard.
