### ISSUE TITLE
sadness-generator: `make_sad`'s iffy unsafety and return type

### ISSUE THREAD

**Issue by vi** [EmbarkStudios/crash-handling#37]
`make_sad`'s signature is

> `pub unsafe fn make_sad(self)`

I see two problems in it:

1. `unsafe` justification is "This is not safe. It intentionally crashes.". As far as I know, crashing (especially in a controlled way) is not unsafe, as it does not lead to undefined behaviour (unless `StackOverflow` variant can somehow not lead to immediate abort or `Segfault` can fails to produce a segfault (e.g. address `0` is actually mapped. In that case it is advisable to fix it to produce reliable segfault e.g. creating a guard page and accessing it) ). If it is not possible for all the cases, at least most of the free-standing functions should be safe to use and remaining `unsafe` markers would tell users which function may fails to produce a clean, controllable crash.

2. Return type of the function is `()`. Should it be `!` instead?

I suppose signature of the function should be like [`std::process::abort`](https://doc.rust-lang.org/stable/std/process/fn.abort.html).

**Comment by Jake-Shadle** [comment]
1. I guess agree to disagree here? It's not about undefined behavior, it's about communicating to the user that in all cases, except 2, `unsafe` code is involved, and that code is _intentionally_ "incorrect" to induce a crash, putting such code behind a safe signature would be misleading at best. As for reliably segfault code, aving null mapped is a niche concern IMO, but I don't particularly care about the implementation as long is is 100% reliable on all targets supported by this lib.
2. `!` is nightly only, once it is stable all of the function can be made to use it instead.

**Comment by vi** [comment]
> 2. `!` is nightly only

As far as I remember, `!` was used in function signatures even before `!` was promoted to a type. It [works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2a278a90c32decf117402147d6ded795) on stable.

**Comment by Jake-Shadle** [comment]
> As far as I remember, ! was used in function signatures even before ! was promoted to a type. It [works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2a278a90c32decf117402147d6ded795) on stable.

I must have been tired when I made that decision since I knew `!` was usable as a function return since eg libc does it, but then when I was originally going to add it the big unstable banner at the top of the Never documentation threw me off. Oops.
