### ISSUE TITLE
Can't build crash-context on arm-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by msirringhaus** [EmbarkStudios/crash-handling#5]
I'm unable to build crash-context on arm-unknown-linux-gnueabihf, either locally (using a raspberry pi) or using github actions: https://github.com/msirringhaus/minidump_writer_linux/actions/runs/1992494641

Unfortunately, the error is only 
> error: could not compile `crash-context` 

even when running `--verbose`.
Is this supposed to work?

**Comment by msirringhaus** [comment]
These are working fine:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

https://github.com/msirringhaus/minidump_writer_linux/actions/runs/1992598643

**Comment by Jake-Shadle** [comment]
Hmm, I will install cross locally and try and figure out what the actual error is, as you say the error output from GHA is useless.

**Comment by Jake-Shadle** [comment]
I can't even get cross working locally at all because I use podman and using main switched to GHCR which doesn't have proper image tags. :stuck_out_tongue:

**Comment by Jake-Shadle** [comment]
I suspected it was the `global_asm!` and sure enough I had missed replacing a preprocessor define with its constant during the port. It gives a not great error when building the package directly, but at least show the line that was problematic, but appears to just entirely give up when being compiled as a dependency, even for crates in the same workspace.

**Comment by Jake-Shadle** [comment]
I've bumped and published crash-context to 0.0.2.

**Comment by dkc6gh** [comment]
I am still having the same issue for ARM v7 cross compilatoin. Somehow inserting "nop" seems to solve the problem for me. Could someone look into this again?

    // Return 0
    "mov   r0, #0",
    "nop",
    "bx    lr",

**Comment by Jake-Shadle** [comment]
Can you please add what target triple doesn't compile and what the compile error actually is? `armv7-unknown-linux-gnueabihf`` compiles just fine.

**Comment by dkc6gh** [comment]
> Can you please add what target triple doesn't compile and what the compile error actually is? `armv7-unknown-linux-gnueabihf` compiles just fine.

Here is the mysterious error message:

error: <inline asm>:23:1: invalid instruction, any one of the following would fix this:
bx    lr
^

error: could not compile `crash-context` (lib)

**Comment by Jake-Shadle** [comment]
Ok well I'm not seeing that, either you are using a different target triple or you're on an older version of rustc?

**Comment by dkc6gh** [comment]
> Ok well I'm not seeing that, either you are using a different target triple or you're on an older version of rustc?

The error only occurs when using the 'release' flag. Building without this flag ('cross build') is successful.

**Comment by Jake-Shadle** [comment]
https://github.com/EmbarkStudios/crash-handling/pull/89
