### ISSUE TITLE
Publish new version for windows-x86 to crates-io

### ISSUE THREAD

**Issue by persytry** [EmbarkStudios/crash-handling#72]
crash-context current version is v.0.5.1 on crates-io, it's not support 32-bit x86 mode, but I saw your github has the file `crash-context/src/windows/ffi/x86.rs` already.
Publish new version for `i686-pc-windows-msvc` please.
Thanks.

**Comment by Jake-Shadle** [comment]
https://github.com/EmbarkStudios/crash-handling/releases/tag/crash-context-0.6.0
