### ISSUE TITLE
Make on_crash callback `FnOnce`

### ISSUE THREAD

**Issue by CrabNejonas** [EmbarkStudios/crash-handling#79]
**Is your feature request related to a problem? Please describe.**
Currently the `on_crash` callback has to be `Fn`, which imposes quite heavy restrictions on the closures user are able to pass.

**Describe the solution you'd like**
If I'm not mistaken the callback will only ever be called once during the lifetime of the instumented app (bc it's gonna crash afterwards) so it should be possible to change the signature to `FnOnce` to allow consumers maximum flexibility (especially use `move closures`)

**Describe alternatives you've considered**

**Additional context**

**Comment by Jake-Shadle** [comment]
Seems reasonable.
